[package]
name = "symbolizer-rs"
version = "0.1.0"
edition = "2021"
authors = ["Axel '0vercl0k' Souchet"]
categories = ["command-line-utilities"]
description = "A fast execution trace symbolizer for Windows that runs on all major platforms and doesn't depend on any Microsoft libraries."
include = ["/Cargo.toml", "/LICENSE", "/src/**", "README.md"]
keywords = ["windows", "kernel", "crash-dump", "symbols", "pdb"]
license = "MIT"
repository = "https://github.com/0vercl0k/symbolizer-rs"
rust-version = "1.70"

[dependencies]
anyhow = "1.0"
pdb = "0.8"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
env_logger = "0.11"
clap = { version = "4.5", features = ["derive"] }
msvc-demangler = "0.10"
ureq = { version = "2.9", default-features = false, features = [
    "tls",
    "gzip",
] }
kdmp-parser = "0.2"
itoa = "1.0.11"

[profile.release]
debug = true
panic = "abort"

[[bin]]
name = "symbolizer-rs"
path = "src/main.rs"
